server.port: 9090
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: 9091
  recommendation-service:
    host: localhost
    port: 9092
  review-service:
    host: localhost
    port: 9093

logging:
  level:
    root: INFO
    hnt: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080

